name: Update Check

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"

  workflow_dispatch:

jobs:
  updatecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run update check script
        env:
          UPDATE_WEB_HOOK: ${{ secrets.UPDATE_WEB_HOOK }}
        run: |
          chmod +x ./scripts/update_check.sh
          ./scripts/update_check.sh